Repository ISIS3510-202410-Team-13/Kotlin, pull requests merged in 2024-04, with the labels that each got.

#43 view fixed
  app/src/main/java/com/example/kotlin/GroupsScreen.kt
  app/src/main/res/drawable/ic_circle_user.xml
Labels: GUI

#41 Internet connectivity
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/kotlin/Helper/ConnectionStatus.kt
  app/src/main/java/com/example/kotlin/Helper/NetworkHelper.kt
Labels: feature

#39 implement local storage for groups
  app/build.gradle.kts
  app/src/main/java/com/example/kotlin/datastore/SQLiteHelperGroups.kt
  gradle/libs.versions.toml
Labels: feature

#40 Local storage for friend
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/kotlin/datastore/SQLiteHelperFriends.kt
Labels: release

#45 24 implement the function to local storage
  .idea/appInsightsSettings.xml
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/kotlin/FriendsScreen.kt
  app/src/main/java/com/example/kotlin/GroupsScreen.kt
  app/src/main/java/com/example/kotlin/Helper/ConnectionStatus.kt
  app/src/main/java/com/example/kotlin/Helper/NetworkHelper.kt
  app/src/main/java/com/example/kotlin/datastore/SQLiteHelperEvents.kt
  app/src/main/java/com/example/kotlin/datastore/SQLiteHelperFriends.kt
  app/src/main/java/com/example/kotlin/datastore/SQLiteHelperGroups.kt
  app/src/main/res/drawable/ic_circle_user.xml
  gradle/libs.versions.toml
Labels: feature

#44 30 implementation to save data is there is no internet connection
  app/src/main/java/com/example/kotlin/FriendsScreen.kt
  app/src/main/java/com/example/kotlin/GroupsScreen.kt
Labels: feature

#46 Migration made succesfully
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/kotlin/MyApi.kt
  app/src/main/java/com/example/kotlin/MyApplication.kt
Labels: bug

#50 36 kotlin completion of add event view
  app/src/main/java/com/example/kotlin/AddEventScreen.kt
  app/src/main/java/com/example/kotlin/CalendarScreen.kt
  app/src/main/java/com/example/kotlin/MainActivity.kt
  app/src/main/res/drawable/ic_arrow_left.xml
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/drawable/ic_person_chalkboard.xml
  app/src/main/res/drawable/ic_signature.xml
  app/src/main/res/drawable/ic_stopwatch.xml
  app/src/main/res/drawable/ic_tag.xml
  gradle/libs.versions.toml
Labels: feature, GUI

#52 Improvements made to view
  app/src/main/java/com/example/kotlin/FriendsScreen.kt
Labels: bug, GUI

#53 Merge develop into main
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/kotlin/AddEventScreen.kt
  app/src/main/java/com/example/kotlin/CalendarScreen.kt
  app/src/main/java/com/example/kotlin/FriendsScreen.kt
  app/src/main/java/com/example/kotlin/GroupsScreen.kt
  app/src/main/java/com/example/kotlin/MainActivity.kt
  app/src/main/java/com/example/kotlin/MyApi.kt
  app/src/main/java/com/example/kotlin/MyApplication.kt
  app/src/main/res/drawable/ic_arrow_left.xml
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/drawable/ic_person_chalkboard.xml
  app/src/main/res/drawable/ic_signature.xml
  app/src/main/res/drawable/ic_stopwatch.xml
  app/src/main/res/drawable/ic_tag.xml
  gradle/libs.versions.toml
Labels: release
