Repository ISIS3510-202410-Team-13/Kotlin, pull requests merged in 2024-03, with the labels that each got.

#5 Feature/home view #1
  .idea/.gitignore
  .idea/deploymentTargetDropDown.xml
  app/build.gradle.kts
  app/src/main/java/com/example/kotlin/CalendarScreen.kt
  app/src/main/java/com/example/kotlin/FriendsScreen.kt
  app/src/main/java/com/example/kotlin/GroupsScreen.kt
  app/src/main/java/com/example/kotlin/HomeScreen.kt
  app/src/main/java/com/example/kotlin/MainActivity.kt
  app/src/main/java/com/example/kotlin/ui/theme/Color.kt
  app/src/main/java/com/example/kotlin/ui/theme/Theme.kt
  app/src/main/java/com/example/kotlin/ui/theme/Type.kt
  app/src/main/res/drawable/bg.jpg
  app/src/main/res/drawable/ic_address_book.xml
  app/src/main/res/drawable/ic_bars.xml
  app/src/main/res/drawable/ic_bell.xml
  app/src/main/res/drawable/ic_calendar.xml
  app/src/main/res/drawable/ic_ellipsis_vertical.xml
  app/src/main/res/drawable/ic_house.xml
  app/src/main/res/drawable/ic_splotch.xml
  app/src/main/res/drawable/ic_user_group.xml
  app/src/main/res/drawable/sticker.png
  app/src/main/res/font/poppins.xml
  app/src/main/res/font/poppins_black.ttf
  app/src/main/res/font/poppins_black_italic.ttf
  app/src/main/res/font/poppins_bold.ttf
  app/src/main/res/font/poppins_bold_italic.ttf
  app/src/main/res/font/poppins_extrabold.ttf
  app/src/main/res/font/poppins_extrabold_italic.ttf
  app/src/main/res/font/poppins_extralight.ttf
  app/src/main/res/font/poppins_extralight_italic.ttf
  app/src/main/res/font/poppins_italic.ttf
  app/src/main/res/font/poppins_light.ttf
  app/src/main/res/font/poppins_light_italic.ttf
  app/src/main/res/font/poppins_medium.ttf
  app/src/main/res/font/poppins_medium_italic.ttf
  app/src/main/res/font/poppins_regular.ttf
  app/src/main/res/font/poppins_semibold.ttf
  app/src/main/res/font/poppins_semibold_italic.ttf
  app/src/main/res/font/poppins_thin.ttf
  app/src/main/res/font/poppins_thin_italic.ttf
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: GUI

#7 Feature/calendar view #2
  .idea/appInsightsSettings.xml
  .idea/gradle.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/misc.xml
  .idea/vcs.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/kotlin/CalendarScreen.kt
  app/src/main/java/com/example/kotlin/FriendScreen.kt
  app/src/main/java/com/example/kotlin/GroupScreen.kt
  app/src/main/java/com/example/kotlin/HomeScreen.kt
  app/src/main/java/com/example/kotlin/MainActivity.kt
  app/src/main/java/com/example/kotlin/MyAppNavigationActions.kt
  app/src/main/java/com/example/kotlin/ui/theme/Type.kt
  app/src/main/res/drawable/address_book.xml
  app/src/main/res/drawable/bars.xml
  app/src/main/res/drawable/bell.xml
  app/src/main/res/drawable/calendar.xml
  app/src/main/res/drawable/house.xml
  app/src/main/res/drawable/plus.xml
  app/src/main/res/drawable/user_group.xml
  app/src/main/res/font/poppins_blackitalic.ttf
  app/src/main/res/font/poppins_bolditalic.ttf
  app/src/main/res/font/poppins_extrabolditalic.ttf
  app/src/main/res/font/poppins_extralightitalic.ttf
  app/src/main/res/font/poppins_lightitalic.ttf
  app/src/main/res/font/poppins_mediumitalic.ttf
  app/src/main/res/font/poppins_semibolditalic.ttf
  app/src/main/res/font/poppins_thinitalic.ttf
  app/src/main/res/layout/activity_horario.xml
  app/src/main/res/layout/activity_horario2.xml
  app/src/main/res/layout/content_horario.xml
  app/src/main/res/layout/content_horario2.xml
  app/src/main/res/layout/fragment_first.xml
  app/src/main/res/layout/fragment_first2.xml
  app/src/main/res/layout/fragment_second.xml
  app/src/main/res/layout/fragment_second2.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/navigation/nav_graph2.xml
  app/src/main/res/values-land/dimens.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values-v23/themes.xml
  app/src/main/res/values-w1240dp/dimens.xml
  app/src/main/res/values-w600dp/dimens.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/themes.xml
  gradle/libs.versions.toml
Labels: GUI

#10 9 implement biometric authentication
  .idea/gradle.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/vcs.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/kotlin/AuthScreen.kt
  app/src/main/java/com/example/kotlin/MainActivity.kt
  app/src/main/java/com/example/kotlin/ui/theme/Theme.kt
  gradle/libs.versions.toml
Labels: feature

#13 Changes made
  app/src/main/java/com/example/kotlin/AuthScreen.kt
  app/src/main/java/com/example/kotlin/CalendarScreen.kt
  app/src/main/java/com/example/kotlin/HomeScreen.kt
  app/src/main/java/com/example/kotlin/MainActivity.kt
Labels: bug, GUI

#14 Notification pops up prompted by button
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/kotlin/GroupsScreen.kt
  app/src/main/java/com/example/kotlin/MyApplication.kt
  app/src/main/java/com/example/kotlin/NotificationService.kt
  gradle/libs.versions.toml
Labels: feature

#16 Create README.md
  README.md
Labels: documentation

#17 15 pseudo view spaces feature
  .idea/.gitignore
  .idea/deploymentTargetDropDown.xml
  .idea/gradle.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/vcs.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/kotlin/CalendarScreen.kt
  app/src/main/java/com/example/kotlin/Classroom.kt
  app/src/main/java/com/example/kotlin/FriendsScreen.kt
  app/src/main/java/com/example/kotlin/GroupsScreen.kt
  app/src/main/java/com/example/kotlin/HomeScreen.kt
  app/src/main/java/com/example/kotlin/MainActivity.kt
  app/src/main/java/com/example/kotlin/MyApi.kt
  app/src/main/java/com/example/kotlin/MyApplication.kt
  app/src/main/java/com/example/kotlin/NotificationService.kt
  app/src/main/java/com/example/kotlin/ui/theme/Color.kt
  app/src/main/java/com/example/kotlin/ui/theme/Theme.kt
  app/src/main/java/com/example/kotlin/ui/theme/Type.kt
  app/src/main/res/drawable/bg.jpg
  app/src/main/res/drawable/ic_address_book.xml
  app/src/main/res/drawable/ic_bars.xml
  app/src/main/res/drawable/ic_bell.xml
  app/src/main/res/drawable/ic_calendar.xml
  app/src/main/res/drawable/ic_ellipsis_vertical.xml
  app/src/main/res/drawable/ic_house.xml
  app/src/main/res/drawable/ic_plus.xml
  app/src/main/res/drawable/ic_splotch.xml
  app/src/main/res/drawable/ic_square_plus.xml
  app/src/main/res/drawable/ic_user_group.xml
  app/src/main/res/drawable/sticker.png
  app/src/main/res/font/poppins.xml
  app/src/main/res/font/poppins_black.ttf
  app/src/main/res/font/poppins_black_italic.ttf
  app/src/main/res/font/poppins_bold.ttf
  app/src/main/res/font/poppins_bold_italic.ttf
  app/src/main/res/font/poppins_extrabold.ttf
  app/src/main/res/font/poppins_extrabold_italic.ttf
  app/src/main/res/font/poppins_extralight.ttf
  app/src/main/res/font/poppins_extralight_italic.ttf
  app/src/main/res/font/poppins_italic.ttf
  app/src/main/res/font/poppins_light.ttf
  app/src/main/res/font/poppins_light_italic.ttf
  app/src/main/res/font/poppins_medium.ttf
  app/src/main/res/font/poppins_medium_italic.ttf
  app/src/main/res/font/poppins_regular.ttf
  app/src/main/res/font/poppins_semibold.ttf
  app/src/main/res/font/poppins_semibold_italic.ttf
  app/src/main/res/font/poppins_thin.ttf
  app/src/main/res/font/poppins_thin_italic.ttf
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/network_security_config.xml
  gradle/libs.versions.toml
Labels: feature, GUI
